name: Python Unit Tests

on:
  push:
    branches:
      - main  # Modify this if your main branch has a different name
  pull_request:
    branches:
      - main  # Modify this if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.3  # Replace 'x' with the desired Python version
        
    - name: Install dependencies
      working-directory: weatherApp
      run: pip install -r requirements.txt  # Modify if your dependencies are listed elsewhere
      
    - name: Run unit tests
      working-directory: weatherApp
      run: python3 -m unittest weatherAppUnitTest.py 
      env:
        API_KEY: ${{ secrets.API_KEY}}

    - name: Run unit tests for basics program
      working-directory: basics
      run: python3 -m unittest hello.py
      



